### ISSUE TITLE
Reducing Omics Data to Common Samples Issue 

### ISSUE THREAD

**Issue by SageSiglerUNCG** [vd4mmind/multiOmicsIntegration#1]
When comparing the list of sample names produced from commonSamples, I find that some of the sample names do not match  the sample name portion of the TCGA barcodes created after the 'Reducing each omics data to common samples only' part of the code is executed. 

I printed out the list of commonSamples and then list(dnaMeth), list(rnaSeq), list(cna) [which returns the column names (i.e., the TCGA barcodes) of each omics data] after the omics data were reduced to the common samples. Then, I searched by the sample names to see which samples were (or weren't) in which lists. For example, I have found the following:
1) '5262-01A' appears in commonSamples, dnaMeth, and rnaSeq, but not cna. 
2) '5259-01A' appears in dnaMeth and rnaSeq, but not cna or commonSamples
3) '5263-10B' appears in cna but not dnaMeth, rnaSeq, or commonSamples

To me this did not make sense, since I thought commonSamples contained all of the common patients among dnaMeth, rnaSeq, and cna, so the reduced omics data should contain those and only those samples that show up in commonSamples and no others. I thought that this matter should be brought to attention.

**Comment by deeplearner87** [comment]
Thanks for bringing this to our notice. We shall look into it and get back asap.

**Comment by deeplearner87** [comment]
Added a fix to the issue with common sample IDs. Changes got reflected in `master`.
