### ISSUE TITLE
feature extration

### ISSUE THREAD

**Issue by MartinChiaHsinLiu** [vd4mmind/multiOmicsIntegration#5]
Hi,
In the DNAm_CNA_to_RNAseq.ipynb, I especially interest in "Dimension Reduction/Feature Extraction using DDAE".
My goal is to decipher what features are important to classify tumor from normal sample.
For example, which gene in RNA or CNV is the most important or with highest weight in the model.
I am interesting in how to extract these information form a trained model?

**Comment by vd4mmind** [comment]
Thanks for your query. This query falls under feature selection and this model doesn't perform feature selection.
